### ISSUE TITLE
doesn't compile on osx 10.9

### ISSUE THREAD

**Issue by olilarkin** [timblechmann/nova-simd#1]
after running cmake . then make

In file included from /Users/oli/Dev/Libraries/nova-simd/testsuite/../detail/define_macros.hpp:23:
/Users/oli/Dev/Libraries/nova-simd/testsuite/../vec/../detail/unroll_helpers.hpp:172:27: fatal error: 
      recursive template instantiation exceeded maximum depth of 256
        vec_type result = f(loaded_in1, loaded_in2, loaded_in3, loaded_in4);
